services:

  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
    restart: unless-stopped
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - 3333:3000
    restart: unless-stopped
    volumes:
      - metabase-storage:/metabase-data

volumes:
  grafana-storage:
  metabase-storage:
