services:

  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
    restart: unless-stopped
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-default_user}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-default_password}
    volumes:
      - mongo-storage:/data/db

volumes:
  grafana-storage:
  mongo-storage:
